version: '3'
services:

  #Notification Db
  publicSale-Notification-db:
    image: "mongo:4.2.3"
    container_name: 'publicSale-Notification-db'
    restart: always 
    ports:
      - 27017:27017
    environment: 
          MONGO_INITDB_ROOT_USERNAME: mongoadmin
          MONGO_INITDB_ROOT_PASSWORD: _Test123

  #RabbitMq
  rabbitmq:
    image: masstransit/rabbitmq:3
    container_name: 'promocode-factory-rabbitmq'
    restart: always 
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
  publicSale-Notification-db-data:
